/**
 * Snowflake AI Coaching Component
 * 
 * Displays personalized coaching feedback after a practice session.
 * Calls the Snowflake Cortex API via backend endpoint.
 */

"use client";

import { useState } from "react";

interface CoachingFeedback {
  success: boolean;
  encouragement: string;
  focus_areas: string[];
  next_steps: string[];
  model: string;
  provider: string;
}

interface SessionData {
  phonemes: string[];
  scores: Record<string, number>;
  struggles: string[];
  duration?: number;
}

export default function SnowflakeCoaching() {
  const [loading, setLoading] = useState(false);
  const [feedback, setFeedback] = useState<CoachingFeedback | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Example: Call this after a practice session
  const getCoachingFeedback = async (sessionData: SessionData) => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("http://localhost:8000/api/coaching-feedback", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(sessionData),
      });

      if (!response.ok) {
        throw new Error(`API error: ${response.status}`);
      }

      const data: CoachingFeedback = await response.json();
      setFeedback(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to get coaching");
    } finally {
      setLoading(false);
    }
  };

  // Example session data
  const handleTestFeedback = () => {
    getCoachingFeedback({
      phonemes: ["AH", "EE", "S"],
      scores: {
        AH: 0.85,
        EE: 0.62,
        S: 0.90,
      },
      struggles: ["inconsistent pitch on EE", "weak vibration"],
      duration: 300, // 5 minutes
    });
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
      <div className="flex items-center justify-between mb-4">
        <h2 className="font-semibold text-lg text-gray-800">
          AI Coaching Feedback
        </h2>
        <div className="text-xs text-gray-500 font-mono">
          Powered by Snowflake Cortex
        </div>
      </div>

      {/* Test button */}
      <button
        onClick={handleTestFeedback}
        disabled={loading}
        className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 text-white py-3 px-6 rounded-lg font-medium hover:from-blue-700 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all mb-4"
      >
        {loading ? "Getting Feedback..." : "Get AI Coaching Feedback"}
      </button>

      {/* Error state */}
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm mb-4">
          ⚠️ {error}
        </div>
      )}

      {/* Feedback display */}
      {feedback && (
        <div className="space-y-4">
          {/* Encouragement */}
          <div className="bg-green-50 border border-green-200 p-4 rounded-lg">
            <div className="text-xs font-semibold text-green-700 uppercase mb-1">
              🎉 Great Work
            </div>
            <div className="text-green-800">{feedback.encouragement}</div>
          </div>

          {/* Focus Areas */}
          {feedback.focus_areas && feedback.focus_areas.length > 0 && (
            <div className="bg-yellow-50 border border-yellow-200 p-4 rounded-lg">
              <div className="text-xs font-semibold text-yellow-700 uppercase mb-2">
                🎯 Focus On
              </div>
              <ul className="space-y-2">
                {feedback.focus_areas.map((area, idx) => (
                  <li key={idx} className="text-yellow-800 text-sm flex items-start">
                    <span className="mr-2">•</span>
                    <span>{area}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Next Steps */}
          {feedback.next_steps && feedback.next_steps.length > 0 && (
            <div className="bg-blue-50 border border-blue-200 p-4 rounded-lg">
              <div className="text-xs font-semibold text-blue-700 uppercase mb-2">
                📝 Next Practice
              </div>
              <ul className="space-y-2">
                {feedback.next_steps.map((step, idx) => (
                  <li key={idx} className="text-blue-800 text-sm">
                    {step}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Model info */}
          <div className="text-xs text-gray-500 text-center pt-2 border-t border-gray-200">
            Generated by {feedback.model} via {feedback.provider}
          </div>
        </div>
      )}

      {/* Instructions when no feedback yet */}
      {!feedback && !loading && !error && (
        <div className="text-center py-8 text-gray-500 text-sm">
          <p>Complete a practice session to get personalized AI coaching.</p>
          <p className="text-xs mt-2">Click the button above to see an example.</p>
        </div>
      )}
    </div>
  );
}
